spring:
  liquibase:
    url: jdbc:postgresql://localhost:5432/customer
    user: postgres
    password: password
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/customer
    username: postgres
    password: password

